# Generated by Django 5.0.6 on 2024-05-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
